eureka:
  instance:
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
#            defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://39.107.226.36:8762/eureka/